### ISSUE TITLE
hi can i write image in the rows?

### ISSUE THREAD

**Issue by pazalvin** [exceljs/exceljs#173] opened 2016-08-24 02:58 UTC
hi can i write image in the rows? your speedy reply is much appreciated :-)

**Comment by guyonroche** [comment] 2016-08-30 17:09
Images are not yet supported. I hope to look into adding them in the not-to-distant future

**Comment by kachkaev** [comment] 2016-09-06 16:49
This issue is probably a duplicate of https://github.com/guyonroche/exceljs/issues/34
Images seem to be in demand! :–) I'd also very like to be able to work with them.

Exceljs has the most convenient API for working with spreadsheets I've seen so far! Once the images are finally removed from the backlog, all competitor libraries will be left far behind!

**Comment by gadiaz1** [comment] 2016-10-13 19:03
+1

**Comment by manuelph** [comment] 2016-11-10 08:30
+1

**Comment by fareshan** [comment] 2016-11-10 22:42
+1

**Comment by manuelph** [comment] 2016-11-18 06:45
can be an alternative, Image is supported
https://www.npmjs.com/package/excel4node

**Comment by manuelph** [comment] 2016-11-18 06:46
![image](https://cloud.githubusercontent.com/assets/8665671/20421283/cf25a2bc-ad9d-11e6-80c7-72c467546265.png)

**Comment by Cliffordwh** [comment] 2017-03-23 15:29
Guys has this feature being created yet? otherwise i would like to write it and create a PR for it!

**Comment by molerat619** [comment] 2018-01-15 18:37
Any news on this one?

**Comment by kachkaev** [comment] 2018-02-20 13:01
@pazalvin does this functionality address your needs?
https://github.com/guyonroche/exceljs#images

If so, feel free to close this issue 😉

**Closed** 2020-01-27 13:41 UTC
