### ISSUE TITLE
The merged cells do not have enough border information

### ISSUE THREAD

**Issue by zengwe** [exceljs/exceljs#635] opened 2018-08-28 10:04 UTC
For example, I merged the cells $B$2:$C$3 and set the outer border to red. I get each cell through EXCELJS, with only the information for the top and left borders.
Then I merged $B$5:$C$6 and set only the top and left borders. The resulting border information is the same as $B$2:$C$3.
So how do I know if the right and bottom borders have color settings?

**Comment by dogusev** [comment] 2019-02-25 13:39
It's an issue, I also faced with it.
It seems that border styles are copied from the master cell, and ignore all others from the merged range

**Comment by cbeltrangomez84** [comment] 2019-08-10 03:47
Is the same #623

**Comment by Toub** [comment] 2020-01-22 05:37
Not sure if it is exactly the same problem, but I provided a simple reproduction code on #623

**Comment by Siemienik** [comment] 2020-01-22 10:05
hmm, it probably happens when you read excel files. 
for a workaround, You may use `cell.master` 
https://github.com/exceljs/exceljs/blob/master/lib/doc/cell.js#L188

When merging cells has been proceded from code it should work ok:
https://github.com/exceljs/exceljs/blob/master/lib/doc/cell.js#L169

I think it's a good topic for pull request if anyone wants :)

**Comment by npmDude** [comment] 2020-01-29 09:17
The reason I think this is happening is because merged cells link their styles from the cell.master which is the top left cell of the merged cells. So when you load a file that has a merged cell it will link its style from the master which only has the top and left borders hence merged cells only has top and left borders. 

The workaround for this one is to set the borders of the master again.

**Comment by npmDude** [comment] 2020-01-30 01:30
The reason this is happening is because when ExcelJS is reading the file it will read the merged cell and link its style based on the master cell (top-left cell). When you merge cells the border style of the master cell will only be on the top and left borders that is why that is the only ones left later on.

But after reading the file, it seems that the link on the style of merged cells is gone that is why when you set the borders for the master again, it is not applying to the other ones.

The workaround for this one is to unmerge the cells programmatically, set the borders of the master cell and merge the cells again.

**Closed** 2020-02-06 23:50 UTC
Labels: bug, enhancement
