### ISSUE TITLE
Issue with borders for merged cell when rewriting an excel workbook

### ISSUE THREAD

**Issue by kami23** [exceljs/exceljs#623] opened 2018-08-02 07:59 UTC
I am using this function to create a copy of my excel file named mytest.xlsx
i have merged cells with borders inside it but in the new file (the copy) some of the merged cells lost their borders i don't know why?  

function createExce()
    {
       workbook.xlsx.readFile('mytest.xlsx')
       .then(function(workbook) {
        // use workbook
return workbook.xlsx.writeFile('new.xlsx');
    });

    }

**Comment by jeremyjh** [comment] 2019-05-13 15:36
@kami23 did you find a workaround for this?

**Comment by kami23** [comment] 2019-05-13 17:07
@jeremyjh no i didn't find a solution for it i had to use a loop to draw all the borders

**Comment by Toub** [comment] 2020-01-22 05:35
I reproduce a similar issue with the following code:

```ts
 const c1 = worksheet.getCell(2, 2);
  c1.border = {
    top: {
      style: 'medium',
      color: { argb: 'FF333333' },
    },
    left: {
      style: 'medium',
      color: { argb: 'FF333333' },
    },
    bottom: {
      style: 'medium',
      color: { argb: 'FF333333' },
    },
    right: {
      style: 'medium',
      color: { argb: 'FF333333' },
    },
  };
  const c2 = worksheet.getCell(3, 3);
  c2.merge(c1);
```
Displayed result with Excel 2016:

![image](https://user-images.githubusercontent.com/367762/72867940-9272bf80-3cf1-11ea-9981-4c7e7930239c.png)

Displayed result with Libre Office 6.1:

![image](https://user-images.githubusercontent.com/367762/72868098-12008e80-3cf2-11ea-82e5-2b7bacac1355.png)

**Comment by npmDude** [comment] 2020-01-29 09:17
The reason I think this is happening is because merged cells link their styles from the cell.master which is the top left cell of the merged cells. So when you load a file that has a merged cell it will link its style from the master which only has the top and left borders hence merged cells only has top and left borders.

The workaround for this one is to set the borders of the master again.

**Comment by npmDude** [comment] 2020-01-30 01:31
The reason this is happening is because when ExcelJS is reading the file it will read the merged cell and link its style based on the master cell (top-left cell). When you merge cells the border style of the master cell will only be on the top and left borders that is why that is the only ones left later on.

But after reading the file, it seems that the link on the style of merged cells is gone that is why when you set the borders for the master again, it is not applying to the other ones.

The workaround for this one is to unmerge the cells programmatically, set the borders of the master cell and merge the cells again.

**Comment by npmDude** [comment] 2020-01-30 01:31
https://github.com/exceljs/exceljs/issues/635#issuecomment-580042923

**Closed** 2020-02-06 10:54 UTC
Labels: bug
