### ISSUE TITLE
Pivot table not working

### ISSUE THREAD

**Issue by aliMalik103** [exceljs/exceljs#1011] opened 2019-10-31 13:06 UTC
After reading excel file i update sheet 2. Pivot table is in sheet one but when i exported the excel Pivot table converted to sheet.

**Comment by guyonroche** [comment] 2019-11-13 08:17
Duplicate of [#1010](https://github.com/exceljs/exceljs/issues/1010)

**Closed by guyonroche** 2019-11-13 08:17 UTC
