### ISSUE TITLE
Incorrect parsing of 1904 Date format

### ISSUE THREAD

**Issue by alexsaves** [exceljs/exceljs#1002] opened 2019-10-26 19:43 UTC
This was interesting. I created a spreadsheet in Google Sheets and exported to XLSX and parsed with ExcelJS and it parses the dates incorrectly (assuming incorrectly that the date values are not 1904 based) I tried to find the problem but it was beyond me to figure this one out. Excel itself parses the dates correctly, FWIW. Here is a sample spreadsheet:

https://drive.google.com/open?id=1atLbfPjD08yVjkGc2VWobUms939C6E-7

**Comment by alexsaves** [comment] 2019-10-26 19:55
I think I mmmight know why. For some reason, Google Sheets exports files using an older schema:

`<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:mv="urn:schemas-microsoft-com:mac:vml" xmlns:mx="http://schemas.microsoft.com/office/mac/excel/2008/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:x14="http://schemas.microsoft.com/office/spreadsheetml/2009/9/main" xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac" xmlns:x15="http://schemas.microsoft.com/office/spreadsheetml/2010/11/main" xmlns:xm="http://schemas.microsoft.com/office/excel/2006/main">
   <workbookPr />
   <sheets>
      <sheet state="visible" name="Repayment History" sheetId="1" r:id="rId3" />
   </sheets>
   <definedNames />
   <calcPr />
</workbook>`

If you look at this Microsoft article (https://support.office.com/en-us/article/date-systems-in-excel-e7fe7167-48a9-4b96-bb53-5612a800b487) it seems to say that the older schemas (pre 2011) assume the 1904 format, rather than the 1900 format:

> Excel 2008 for Mac and earlier Excel for Mac versions calculate dates based on the 1904 date system. Excel 2016 for Mac and Excel for Mac 2011 use the 1900 date system, which guarantees date compatibility with Excel for Windows.

so... yeah. That might be why Excel reads these dates correctly?

**Comment by alexsaves** [comment] 2019-10-26 20:34
OK no this was a red herring. Even when I factor in the schema version and assume 1904 - while it gets the month and day right, the YEAR is wrong. Something else fundamental is borked. Maybe the authors of ExcelJS can figure this one out.

**Comment by alexsaves** [comment] 2019-10-26 20:45
[datetest.xlsx](https://github.com/exceljs/exceljs/files/3775258/datetest.xlsx)

**Comment by guyonroche** [comment] 2019-10-28 08:19
@alexsaves - I've looked at your PR and I'm not sure I'm reproducing your problem.
First of all, I think the integration test is a bit flawed - Mar 01 2017 is a Wednesday, not a Thursday so the expect would never succeed, also, comparing with toString() is brittle as it will be locale dependent.

The numerical value stored in A1 (42795) seems consistent with the results I see of "Wed Mar 01 2017 00:00:00 GMT+0000 (Greenwich Mean Time)" (I'm in London)

**Comment by alexsaves** [comment] 2019-10-30 02:22
I've cleaned up the PR based on your feedback but I'm still seeing the issue. I hope its a bit clearer for you to see (or invalidate outright as the case may be). The test is still failing but I think the test itself is correct now. Also if you open the excel file in Excel you should see March 1, 2017, not February.

**Comment by guyonroche** [comment] 2019-11-13 08:02
Closing this as issue was caused by time-zone handling

**Closed by guyonroche** 2019-11-13 08:02 UTC
