### ISSUE TITLE
[BUG] Huge size increase in 3.8.2 -> 3.9.0

### ISSUE THREAD

**Issue by mydea** [exceljs/exceljs#1236] opened 2020-04-27 11:43 UTC
## 🐛 Bug Report

I wasn't quite sure if this would be a bug or a feature improvement, but I noticed that the jump from 3.8.2 to 3.9.0 lead to an increase of 156 kb, or 36kb gzipped, of the size of the library. 

You can also see this here:
https://bundlephobia.com/result?p=exceljs@3.9.0

From scanning the commits, it is not clear to me what feature lead to this quite massive increase - I am also not sure if that was "on purpose" or just happened somehow.

Lib version: 3.9.0

## Steps To Reproduce

See: https://bundlephobia.com/result?p=exceljs@3.9.0
Which was also confirmed by our CI, which shows the bundle size increasing massively.

## The expected behaviour:

A minor version bump that is not introducing massive new features shouldn't increase the bundle size by over 150 kb.

## Possible solution (optional, but very helpful):

* What exactly lead to this bundle size increase?

**Comment by alubbe** [comment] 2020-04-28 15:43
hi @mydea thanks for the report! I'm not sure this tool is a good measure, it seems to `npm install` and measure the folder size. We bundle a lot of stuff, incl. the actual source code, a few ES5 transpiled versions and docs. Feel free to investigate if the (es5) browser bundle has seen any size increases, then we can investigate that further.

**Comment by mydea** [comment] 2020-04-29 06:47
We get the same size increase in our application build output!

**Comment by alubbe** [comment] 2020-04-29 09:27
Looked into it, it seems to be caused by babel: https://github.com/babel/babel/blob/master/CHANGELOG.md#v795-2020-04-07
The two changes to `createSuper` print a lot of new code that is replicated for each file in our code base and every dependency. It might be that there is a smarter way to not replicate these babel helpers as much - if you have a suggestion to improve our build setup, I'd love to try that out: https://github.com/exceljs/exceljs/blob/master/gruntfile.js

**Comment by mydea** [comment] 2020-04-29 10:47
Hmm, I have tried downgrading @babel/core all the way down to 7.5 and always get the same output file size, so I don't think it is (only) that which causes the size increase.

I have checked it out locally, and the gzipped size of the excel.min.js increased here:

Baseline 2.8.2: 231kb

* https://github.com/exceljs/exceljs/pull/1140 231kb -> 241kb
* https://github.com/exceljs/exceljs/pull/1193 241kb -> 264kb

For the later, bigger jump, concretely it seems to be this commit: https://github.com/exceljs/exceljs/pull/1193/commits/f345addc5726aad65d266904eb3f4edd508c56c1 which made it grow from 242->264

I will try to see if I can find out anything more.

**Comment by mydea** [comment] 2020-04-29 11:44
OK, I did some further digging.

For the 231 -> 241kb increase, the root seems to be this commit:
https://github.com/exceljs/exceljs/pull/1140/commits/16ef74e6088b659969289a3ccb4c9af9ef327cc7

I suspect it is because of [readable-stream](https://github.com/nodejs/readable-stream)

For the 242->264kb increase, the source is [regexpu-core](https://github.com/mathiasbynens/regexpu-core).

IMHO it is not a great tradeoff at this time to increase bundlesize by 10% for IE11 support of complex regex patterns.

I think it would be reasonable to require host applications to define a polyfill like this on their own, as more and more applications (like ours) do not need to support IE11 anymore.

Regarding the readable-streams functionality, I guess this is a bit trickier to solve...!

**Comment by alubbe** [comment] 2020-04-29 15:36
Downgrading @babel/core itself doesn't do anything, you'll need to downgrade babel-plugin-transform-classes, babel-plugin-proposal-class-properties, babel-plugin-proposal-decorators, babel-plugin-transform-classes, babel-plugin-transform-parameters, babel-plugin-transform-runtime, babel-plugin-transform-typescript, babel-preset-env

But anyways, paying that extra price is just part of using babel. Similarly, adding readable-stream helps to ensure the we use the same stream api everywhere, which I would consider worth it. Regarding `regexpu-core`, I think you make a great argument, I think we should remove that again.

Just for fun, could you try to use webpack instead of grunt, based on babel and terser? I have a strong suspicion that that might make for a smaller bundle.

**Comment by mydea** [comment] 2020-04-30 11:13
I am by no means a Webpack expert, but I put something together here: https://github.com/mydea/exceljs/tree/use-webpack

However, that seems to generate a _bigger_ output than before, seen here: 
https://github.com/mydea/exceljs/pull/3

There might be ways to further optimize this, however I don't really have much experience with this :/

**Comment by alubbe** [comment] 2020-05-25 08:28
Should be fixed with https://github.com/exceljs/exceljs/pull/1297

**Closed** 2020-05-26 09:03 UTC

**Comment by jeffersoneagley** [comment] 2020-06-12 02:06
Just to share some knowledge here, because this package is kind of huge and only used on an edge case, I ended up using an inline import to codesplit it into a secondary bundle that's loaded as-needed:
```
const wb = new (await import('exceljs')).Workbook();
```

May be helpful for anybody else out there who's running into "this is 25% of my bundle" problems. :)
