### ISSUE TITLE
[Q]limit column

### ISSUE THREAD

**Issue by ayushkumar9333** [exceljs/exceljs#1265] opened 2020-05-11 09:29 UTC
i have 6 column fields in my code. i want only columns A to F be there when i export with rest columns hidden or locked so viewing the new created excel doesn't show any column beyond F.

how to do so. i am using angular 6 to create excel. and using excelsjs through npm

**Comment by rahuljoshi00794** [comment] 2020-05-12 08:26
i am also trying to do same thing but not able to achieve this. i want only  6 columns and 2000 rows to be visible in exported excel rest of them should be hidden. how can we do it?. can anybody help me on this. 
thanks in advance

**Comment by Alanscut** [comment] 2020-05-22 07:06
duplicate of #1284.

**Closed by Alanscut** 2020-05-22 07:06 UTC
