### ISSUE TITLE
Image position - stretching image

### ISSUE THREAD

**Issue by Trynex** [exceljs/exceljs#467] opened 2017-12-20 08:04 UTC
Hello everyone. I have a problem with images using exceljs. If I just run excel file through and save it, images are immediately deformed (stretched). I tried workaround and so I just removed images from original excel file and inserted them with add image. Again stretched. So I tried not to specify cells for image to include, but also other(more specific option):

`{tl: { col: 1.2, row: 0.4 }, br: { col: 3.2, row: 0.9 }}`

This worked when row number was not decimal. Because the example above didn't scale the image
from 0.4 to 0.9 of the cell, but rather deformed it .. Which is weird as the image started the position on 0.4. This for example worked fine:

`{tl: { col: 1.2, row: 0.4 }, br: { col: 3.2, row: 1 }}`

but any decimal number in br->row does weird things. 

I also tried to specify editAs attribute and all its options, but no luck there.

Am I doing something wrong or is it a bug? Is there any workaround where I can specify the place where I want to include image without stretching image?

Thank you for your help!

**Comment by jwmann** [comment] 2018-01-17 15:27
I'm having a similar issue in where the `row` property isn't being respected.
In my case though, I _want_ to resize the image.

````
  // Add the Header Image
  sheet.mergeCells('A1:E1');
  const imageRow = sheet.getRow(1);
  imageRow.height = 60;
  const headerImage = workbook.addImage({
    base64: headerImg,
    extension: 'png',
  });
  sheet.addImage( headerImage, {
    tl: { col: 0.1, row: 0.3},
    br: { col: 2.0, row: 0.99999999999}
  });
````
![screen shot 2018-01-17 at 10 22 59](https://user-images.githubusercontent.com/436270/35050335-91166de0-fb70-11e7-8311-7499910ca523.png)

If I make `br: { col: 2.0, row: 1}` That pixelated image stretches ALL the way to the full height of Row 1.

Do you see the discrepancy here?
It's as if the height change is being ignored and row doesn't care. The `col` prop seems to work fine though.

**Comment by jwmann** [comment] 2018-01-17 16:29
I decided that maybe I could avoid this and pre-size my actual image first and use `editAs: 'absolute'` but that makes it stretch the image anyway.

There seems to be something fundamentally broken in this function.

**Comment by Trynex** [comment] 2018-01-17 18:01
Hi man. I know what you mean, I  tried everything with this plugin but it didnt work. So I had to fork this package and fix it. Currently I'm not near PC but tomorrow I will write you how to use my modified version to make pictures scalable any way you want.

**Comment by jwmann** [comment] 2018-01-17 20:36
Sounds good, perhaps we could make a PR with these fixes too? :)

**Comment by Trynex** [comment] 2018-01-18 06:17
So as promised this is my fork of ExcelJS: https://github.com/Trynex/exceljs 
The thing is that (after few hours debugging their code) I found they use fixed height and width of cells to calculate the position of your image. I had to break down excel (unzip it and look into the standard what is excel's structure) and I found out that first you have to specify where your image starts and ends (cell-wise: row and col property of model)  and than colOff and rowOff is actuall stretching/position inside the cell of the image. This is what was calculated wrong and I didn't find any possibility to calculate colOff and rowOff easily and dynamically(since you would need to know the width and height of cells you insert the image into). So what I did is I added two new properties colOff and rowOff (obviously) for each of two existing tl and br properties. As you know from documentation tl is top left corner (cell wise) and br is bottom right. But now you need stretching right to specify like part of the cell where you want it.

(TLDR starts here:)

So basic example in original:
{
    "tl": { "col": 1, "row": 0},
    "br": { "col": 3, "row": 0},
    "editAs" : "absolute"
}

But that stretches the wrong way as your cell width and height is not accounted for in calculation. So what you want to do here is to add specific position in the cell where these top left and bottom right corners will start in pixels. 

Example with my fix:
{
     "tl": { "col": 1, "row": 0, "colOff": 6, "rowOff": 14},
    "br": { "col": 3, "row": 0, "colOff": 76, "rowOff": 55},
    "editAs" : "absolute"
 }

Try to play with it little and ask if you need any help.

**Comment by dmastag** [comment] 2018-02-22 08:51
@Trynex interesting way of going around this issue.
Would it not be more practical to account the cell height and weight in the calculation or is this something that is not possible?

**Comment by robsco-git** [comment] 2018-03-17 22:19
One can also use the [sharp](https://github.com/lovell/sharp) image processing library to add a transparent (or white) background to an image and scale the image whilst retaining it's aspect ratio. Then, placing this square image into a square cell will display it with the correct aspect ratio. Maybe an image is a simpler way of explaining:

![screenshot from 2018-03-18 00-11-59](https://user-images.githubusercontent.com/3826617/37560457-fea643b8-2a40-11e8-8b2b-81a5c0ad4ce4.png)

The ratio between width an height in this library seems to be 0.14291498 (IDK why?). In other words, one can set col.width = 10 * 1.429149798 and row.height = 100 to get a square cell. Then, you can use the following sharp snippet to scale the image, preserving the aspect ratio and adding a white background to the image in the places where extra space is needed to keep the image square.

```
sharp(image)
      .resize(scale, scale)
      .background({r: 255, g: 255, b: 255})
      .embed()
      .toBuffer()
      .then(data => {
        // do something
      })
```

One could use this snippet to use a transparent background

```
sharp(image)
      .resize(scale, scale)
      .background({r: 0, g: 0, b: 0, alpha: 0})
      .embed()
      .toFormat(sharp.format.png)
      .toBuffer()
      .then(data => {
        // do something
      })
```

Super duper hacky but I got a working solution for my use case. Whether or not this will help you depends on your use case.

**Comment by jwmann** [comment] 2018-04-26 15:02
I'm just wondering why @Trynex's fix isn't pulled into master. It's an actual bug that `editAs: 'absolute'` doesn't actually do what it says.

**Comment by Pipoupi** [comment] 2018-11-09 08:35
@FelipeRobles92 This may be because you forgot to quote your file name 
```
 workbook.xlsx.writeBuffer({
            base64: true
        }).then(buffer => FileSaver.saveAs(new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}), `${Date.now()}_feedback.xlsx`)).catch(err => console.log('Error writing excel export', err))
    });
```

**Comment by FelipeRobles92** [comment] 2018-11-09 13:03
it just happens to me when export excel with image :(

**Comment by kaidoj** [comment] 2018-11-14 11:47
I can confirm. This issue is still there. Same problem as OP posted.

**Comment by Siemienik** [comment] 2018-12-01 12:14
@Trynex @jwmann @dmastag 
Hello guys, i fix it in pull request #702, 
comparing it to #691, i care about backward compatibility and write some test to ensure it works well.

if You need this changes quicly, i have build branch in my repo: 
https://github.com/p3rio/exceljs/tree/build

npm:
```
    "dependencies": {
        "exceljs": "github:p3rio/exceljs#build"
    }
```

**Comment by kaidoj** [comment] 2018-12-08 13:02
@Siemienik as soon as i get back to that project where i used exceljs, i will try out your fix and see if that fixes my problem. Ofc its better to have tests etc. I just did it to fix my issue fast without going too deep into execeljs code.

**Comment by dogusev** [comment] 2019-04-08 20:51
@alubbe @guyonroche 
Hi!
An issue, which was resolved after #702 merged - came back again. Something happened, and images again stretched

**Comment by Siemienik** [comment] 2019-04-17 13:14
> An issue, which was resolved after #702 merged - came back again. Something happened, and images again stretched

any one found reason of that?

**Comment by dogusev** [comment] 2019-04-17 13:52
probably mess in installed dependencies. Can not reproduce it again

**Comment by Siemienik** [comment] 2019-04-18 13:17
So .. does the bug still exists or was it fixed?

**Comment by dogusev** [comment] 2019-04-18 13:42
as for me, i cannot reproduce it again. So i'd say it's fixed

**Closed** 2019-04-19 10:28 UTC

**Comment by ShraddhaJ11** [comment] 2020-06-16 10:55
> "editAs" : "absolute"



> So as promised this is my fork of ExcelJS: https://github.com/Trynex/exceljs
> The thing is that (after few hours debugging their code) I found they use fixed height and width of cells to calculate the position of your image. I had to break down excel (unzip it and look into the standard what is excel's structure) and I found out that first you have to specify where your image starts and ends (cell-wise: row and col property of model) and than colOff and rowOff is actuall stretching/position inside the cell of the image. This is what was calculated wrong and I didn't find any possibility to calculate colOff and rowOff easily and dynamically(since you would need to know the width and height of cells you insert the image into). So what I did is I added two new properties colOff and rowOff (obviously) for each of two existing tl and br properties. As you know from documentation tl is top left corner (cell wise) and br is bottom right. But now you need stretching right to specify like part of the cell where you want it.
> 
> (TLDR starts here:)
> 
> So basic example in original:
> {
> "tl": { "col": 1, "row": 0},
> "br": { "col": 3, "row": 0},
> "editAs" : "absolute"
> }
> 
> But that stretches the wrong way as your cell width and height is not accounted for in calculation. So what you want to do here is to add specific position in the cell where these top left and bottom right corners will start in pixels.
> 
> Example with my fix:
> {
> "tl": { "col": 1, "row": 0, "colOff": 6, "rowOff": 14},
> "br": { "col": 3, "row": 0, "colOff": 76, "rowOff": 55},
> "editAs" : "absolute"
> }
> 
> Try to play with it little and ask if you need any help.

@Trynex  How to calculate coloff and rowoff and what is the unit of coloff and rowoff ?

**Comment by sourvil** [comment] 2020-08-31 10:54
still not working and calculating rowOff & colOff is not clear

**Comment by premdasvm** [comment] 2021-04-05 16:59
I'm trying to add an image to a specific cell, is there any way I can adjust the image size or the cell size so it can fit on the cell.?

```js
    result.map(order => {
      const worksheet = workbook.addWorksheet(order.branch_code);

      worksheet.columns = [
        { header: 'Id', key: 'id', width: 10 },
        { header: 'Product Code', key: 'pcode', width: 20 },
        { header: 'Image', key: 'image', width: 50 },
      ];

      order.products.map(product => {
        const imageId = workbook.addImage({
          filename: `${PRODUCT_IMAGE_PATH}/${product.image}`,
          extension: 'jpeg',
        });

        worksheet.addRow({ id: product.products.id, pcode: product.products.product_code });
        worksheet.addImage(imageId, `C${position}:C${position}`);
        position++;
      });
    });

    await workbook.xlsx.writeFile('export.xlsx');
    ```
    
![image](https://user-images.githubusercontent.com/14838550/113600879-42fe8200-965e-11eb-9d22-54d921588b10.png)


but it looks like this, how can I fix this.?
