### ISSUE TITLE
A parameter initializer is only allowed in a function or constructor implementation

### ISSUE THREAD

**Issue by pramodjaiswalapp** [exceljs/exceljs#779] opened 2019-04-08 06:05 UTC
Why i am getting this error in node module.
node_modules/exceljs/index.d.ts:787:14 - error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

787  constructor(model: IAnchor|object = {});

**Comment by alubbe** [comment] 2019-04-08 14:46
Duplicate of https://github.com/exceljs/exceljs/issues/773 - we're working on it

**Closed by alubbe** 2019-04-08 14:46 UTC
